name: Go Tests

on: [push]

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22.0' ]
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          go:
            - 'go/**/**'
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Display Go version
      if: steps.filter.outputs.go == 'true'
      run: go version
    - name: workflow tests
      if: steps.filter.outputs.go == 'true'
      run: go test ./... -v

